### ISSUE TITLE
dotenvはソースコードに埋めたくない

### ISSUE THREAD

**Issue by ssssota** [nori3636/discordbot_codehighlight#9]
ref. https://blog.leko.jp/post/you-might-not-need-dotenv-in-source/

## WHAT

dotenvをdevDependenciesにした上で、起動コマンドに `-r dotenv/config` オプションを追加する

**Comment by ssssota** [comment]
herokuの環境変数の仕組みはあんま調べてない

**Comment by ssssota** [comment]
https://devcenter.heroku.com/ja/articles/config-vars#using-the-heroku-dashboard

**Comment by norikmb** [comment]
> dotenvをdevDependenciesにした上で、起動コマンドに -r dotenv/config オプションを追加する

これがうまくいかない

**Comment by ssssota** [comment]
どううまく行ってないのかがわからないと助言できないです…

**Comment by norikmb** [comment]
Herokuではdotenvを利用してないため、ローカル環境で動かすためにenvファイルを利用してます。
npm startに上記を書きましたが、以下のエラーが出ます
```
C:\Users\norik\workspace\discordbot\Discordbot\node_modules\discord.js\src\client\Client.js:228
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\norik\workspace\discordbot\Discordbot\node_modules\discord.js\src\client\Client.js:228:52)
    at Object.<anonymous> (C:\Users\norik\workspace\discordbot\Discordbot\src\index.js:173:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'
}
```
